### ISSUE TITLE
Tray icon not working properly

### ISSUE THREAD

**Issue by ZhaoZuohong** [ustcpetergu/SiliTune#2]
# Tray icon not working properly

### Not showing in KDE

Tray icon does not show in KDE.

### Changing profile crashes

I then tried it on IceWM. After starting the program, the tray icon appeared. Function show, hide and exit works properly but changing power profile causes the program to exit immediately.

**Comment by regymm** [comment]
Yes changing profiles in tray icon cause the program to crash, it's a bug. I'll fix it later.
The icon-not-shown problem is likely to be DE-specific.

**Comment by regymm** [comment]
Fixed.
